---

- name: add remi PHP repository
  ansible.builtin.dnf:
    name: "https://rpms.remirepo.net/fedora/remi-release-39.rpm"
    state: present
  when: ansible_distribution == "Fedora"

- name: enable PHP {{ php_version }} remi repo
  shell: "dnf module enable php:remi-{{ php_version }} -y"

- name: install php package and common extensions
  ansible.builtin.dnf:
    name:
      - php
      - php-common
      - php-cli
      - php-mysqlnd
      - php-gd
      - php-curl
      - php-json
    update_cache: true
  when: ansible_distribution == "Fedora"

