---
- name: update repository index
  apt:
    update_cache: yes
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: upgrade server distribution
  apt:
    upgrade: dist
  when: ansible_distribution in ["Debian", "Ubuntu"]
