---
- name: install pre-requirements
  apt:
    pkg:
      - unzip
      - software-properties-common
      - python3
      - python3-pip
      - python3-setuptools
      - virtualenv
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - curl
      - git
      - wget
      - apache2-utils
      - gnupg-agent
      - software-properties-common
    state: present
