---
- name: install essential utility packages
  ansible.builtin.package:
    name:
      - git
      - autoconf
      - libtool
      - automake
      - build-essential
      - gettext
      - cmake
      - python3-full
      - python3-pip
    state: present
