---
- name: clone a github repository
  become: false
  ansible.builtin.git:
    repo: https://github.com/gpproton/shell-assist.git
    dest: $HOME/shell-assist
    clone: yes
    update: yes
    force: yes

- name: setup personal path file
  become: false
  ansible.builtin.copy:
    src: sharedrc.sh
    dest: $HOME/.sharedrc
    mode: 0755

- name: setup shell assist alias
  become: false
  ansible.builtin.blockinfile:
    path: $HOME/.zshrc
    insertafter: EOF
    state: present
    block: |
      # shared source definitions
      if [ -f $HOME/.sharedrc ]; then
          source $HOME/.sharedrc
      fi
