---
- name: create .dotnet directory
  ansible.builtin.file:
    path: "$HOME/.dotnet"
    state: directory
    mode: 0775

- name: setup dotnet installer binary
  ansible.builtin.get_url:
    url: "https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh"
    dest: "$HOME/.dotnet/dotnet-install"
    mode: a+x

- name: setup dotnet LTS version
  ansible.builtin.shell: "$HOME/.dotnet/dotnet-install -c LTS --install-dir $HOME/.dotnet"

- name: install additional dotnet packages
  become: true
  ansible.builtin.package:
    state: present
    name:
      - mono-devel

- name: install basic workloads
  ansible.builtin.shell: "$HOME/.dotnet/dotnet workload install wasm-tools wasm-experimental"

