---
- name: switch default shell to zsh
  ansible.builtin.shell: "chsh -s $(which zsh)"

- name: setup shopt workaroud for zsh
  ansible.builtin.copy:
    src: shopt
    dest: /usr/bin/shopt
    owner: root
    group: root
    mode: 0755

- name: setup zsh options for {{ lookup('env', 'USER') }}
  ansible.builtin.include_role:
    name: viasite-ansible.zsh
  vars:
    zsh_user: "{{ lookup('env', 'USER') }}"
    zsh_powerlevel9k_always_show_context_bool: false
    # zsh_hotkeys_extras:
    #   - { hotkey: '^r', action: fzf-history }

- name: tweak powerlevel display
  become: false
  ansible.builtin.lineinfile:
    path: "$HOME/.p10k.zsh"
    create: true
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  with_items:
    - key: POWERLEVEL9K_SHORTEN_DIR_LENGTH
      value: 1
    - key: POWERLEVEL9K_SHORTEN_STRATEGY
      value: truncate_to_last

- name: fix for zsh error
  become: false
  ansible.builtin.blockinfile:
    path: $HOME/.zshrc
    insertafter: "antigen version: "
    state: present
    block: |
      alias shopt='/usr/bin/shopt'
      [[ ! -f ~/.bashrc ]] || source ~/.bashrc

- name: clone zsh-autocomplete
  become: false
  ansible.builtin.git:
    repo: https://github.com/marlonrichert/zsh-autocomplete.git
    dest: $HOME/zsh-autocomplete
    clone: yes
    update: yes

- name: setup zsh-autocomplete
  become: false
  ansible.builtin.blockinfile:
    path: $HOME/.zshrc
    insertafter: EOF
    state: present
    block: |
      # additonal setup for zsh completion
      source $HOME/zsh-autocomplete/zsh-autocomplete.plugin.zsh
