---
namespace: gpproton
name: core
version: 0.0.1
readme: README.md
license_file: LICENSE.md
authors:
  - radioActive DROID <me@godwin.dev>
description: Personal ansible collection
license:
  - MIT
dependencies: {}
tags:
  - gpproton
  - common
  - collection
  - random
  - linux
  - windows
  - util
  - docker
  - kubernetes
  - infrastructure
  - terraform
repository: https://github.com/gpproton/ansible-collections
documentation: https://github.com/gpproton/ansible-collections
issues: https://github.com/gpproton/ansible-collections/issues
build_ignore:
  - .gitignore
