---
- name: setup zsh/cli options
  ansible.builtin.include_tasks:
    file: setup-cli.yml
    apply:
      become: true

- name: setup github packages for Fedora
  ansible.builtin.include_tasks:
    file: setup-github.yml
    apply:
      become: true
  when: ansible_distribution == "Fedora"

- name: setup virtualization and general dev packages for Fedora
  ansible.builtin.include_tasks:
    file: fedora-setup-general.yml
    apply:
      become: true
  when: ansible_distribution == "Fedora"
