---
- name: setup zsh/cli options
  ansible.builtin.include_tasks:
    file: setup-cli.yml
    apply:
      become: true

- name: setup github packages for Fedora
  ansible.builtin.include_tasks:
    file: setup-github.yml
    apply:
      become: true
  when: ansible_distribution == "Fedora"

- name: setup virtualization and general dev packages for Fedora
  ansible.builtin.include_tasks:
    file: fedora-setup-general.yml
    apply:
      become: true
  when: ansible_distribution == "Fedora"

- name: setup docker packages for Fedora
  ansible.builtin.include_tasks:
    file: fedora-docker.yml
    apply:
      become: true
  when: ansible_distribution == "Fedora"

- name: setup dotnet for unix
  ansible.builtin.include_tasks:
    file: setup-dotnet.yml
    apply:
      become: false

- name: setup PHP for Fedora
  ansible.builtin.include_tasks:
    file: setup-php.yml
    apply:
      become: true
  when: ansible_distribution == "Fedora"

- name: setup nodejs for unix
  ansible.builtin.include_tasks:
    file: setup-nodejs.yml
    apply:
      become: false

- name: setup jdk for unix
  ansible.builtin.include_tasks:
    file: setup-jdk.yml
    apply:
      become: false
