---
- name: switch default shell to zsh
  ansible.builtin.shell: "chsh -s $(which zsh)"

- name: setup shopt workaroud for zsh
  ansible.builtin.copy:
    src: shopt
    dest: /usr/bin/shopt
    owner: root
    group: root
    mode: 0755

- name: setup zsh options for {{ lookup('env', 'USER') }}
  ansible.builtin.include_role:
    name: viasite-ansible.zsh
  vars:
    zsh_user: "{{ lookup('env', 'USER') }}"
    zsh_powerlevel9k_always_show_context_bool: false

- name: tweak powerlevel display
  become: false
  ansible.builtin.lineinfile:
    path: "$HOME/.p10k.zsh"
    create: true
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  with_items:
    - key: POWERLEVEL9K_SHORTEN_DIR_LENGTH
      value: 1
    - key: POWERLEVEL9K_SHORTEN_STRATEGY
      value: truncate_to_last

- name: install powerline fonts in Fedora
  ansible.builtin.dnf:
    name: powerline-fonts
    state: present
  when: ansible_distribution == "Fedora"

- name: fix for zsh error
  become: false
  ansible.builtin.blockinfile:
    path: $HOME/.zshrc
    insertafter: "antigen version: "
    state: present
    block: |
      alias fdfind='fd'
      alias shopt='/usr/bin/shopt'
      [[ ! -f ~/.bashrc ]] || source ~/.bashrc

- name: clone a github repository
  become: false
  ansible.builtin.git:
    repo: https://github.com/marlonrichert/zsh-autocomplete.git
    dest: $HOME/zsh-autocomplete
    clone: yes
    update: yes

- name: clone a github repository
  become: false
  ansible.builtin.git:
    repo: https://github.com/gpproton/shell-assist.git
    dest: $HOME/shell-assist
    clone: yes
    update: yes
    force: yes

- name: create alias file
  become: false
  ansible.builtin.file:
    state: touch
    path: $HOME/.sharedrc

- name: setup shell assist alias
  become: false
  ansible.builtin.blockinfile:
    path: $HOME/.sharedrc
    insertafter: EOF
    state: present
    block: |
      source $HOME/zsh-autocomplete/zsh-autocomplete.plugin.zsh
      eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      ALIAS_PATH="$HOME/shell-assist/alias"
      if [ -d $ALIAS_PATH ]; then
        for rc in $ALIAS_PATH/*.sh; do
          if [ -f $rc ]; then
            source $rc
          fi
        done
      fi
      
      ## start dotnet
      export DOTNET_ROOT={{ dotnet_path }}
      export PATH=$PATH:$DOTNET_ROOT
      export PATH=$PATH:$DOTNET_ROOT/tools
      export ASPNETCORE_Kestrel__Certificates__Default__Password=""
      export ASPNETCORE_Kestrel__Certificates__Default__Path="$HOME/localhost.pfx"
      ## end dotnet

- name: setup shell assist alias
  become: false
  ansible.builtin.blockinfile:
    path: $HOME/.bashrc
    insertafter: EOF
    state: present
    block: |
      # shared source definitions
      if [ -f $HOME/.sharedrc ]; then
          . $HOME/.sharedrc
      fi

