---
- name: update all packages
  ansible.builtin.include_tasks:
    file: update-packages.yml
    apply:
      become: true

- name: upgrade all packages
  ansible.builtin.include_tasks:
    file: upgrade-packages.yml
    apply:
      become: true

- name: setup additional repository for Fedora
  ansible.builtin.include_tasks:
    file: fedora-repositories.yml
    apply:
      become: true
  when: ansible_distribution == "Fedora"

- name: setup essential packages
  ansible.builtin.include_tasks:
    file: essential-packages.yml
    apply:
      become: true

- name: fonts setup
  ansible.builtin.include_tasks:
    file: font-setup.yml
    apply:
      become: true

- name: homebrew setup
  ansible.builtin.include_tasks:
    file: homebrew-setup.yml
    apply:
      become: true

