---
- name: dnf config change fastestmirror
  community.general.ini_file: dest=/etc/dnf/dnf.conf  section=main option=fastestmirror value=1 backup=yes
  tags: configuration

- name: dnf config change max_parallel_downloads
  community.general.ini_file: dest=/etc/dnf/dnf.conf  section=main option=max_parallel_downloads value=10 backup=yes
  tags: configuration

- name: dnf config change deltarpm
  community.general.ini_file: dest=/etc/dnf/dnf.conf  section=main option=deltarpm value=true backup=yes
  tags: configuration
