---
- name: check OS details
  debug:
    msg: '{{ ansible_distribution }} - {{ ansible_distribution_major_version }}'

- name: setup users defaults
  ansible.builtin.include_tasks:
    file: users.yml
    apply:
      become: true

- name: fedora dnf config
  ansible.builtin.include_tasks:
    file: fedora-default-config.yml
    apply:
      become: true
  when: ansible_distribution == "Fedora"
