---
- ansible.builtin.include_tasks:
    file: timezone-config.yml
    apply:
      become: true
  when: setup_timezone == True

- ansible.builtin.include_tasks:
    file: host-file-config.yml
    apply:
      become: true
  when: setup_hosts == True

- ansible.builtin.include_tasks:
    file: system-limits.yml
    apply:
      become: true
  when: setup_limit == True

- ansible.builtin.include_tasks:
    file: system-ulimits.yml
    apply:
      become: true
  when: setup_ulimit == True

- ansible.builtin.include_tasks:
    file: grub-setup.yml
    apply:
      become: true
  when: setup_grub == True
