---
- name: configure system ulimit values for all
  pam_limits:
    domain: "*"
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
    dest: "{{ ulimit_dest }}"
    backup: "{{ ulimit_backup }}"
  with_items: "{{ ulimits_config }}"

- name: configure system ulimit values for root
  pam_limits:
    domain: root
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
    dest: "{{ ulimit_dest }}"
    backup: "{{ ulimit_backup }}"
  with_items: "{{ ulimits_config }}"

- name: reload settings from all system configuration files
  shell: sysctl --system
