- name: Ensuring Homebrew Is Installed
  ansible.builtin.stat:
    path: /usr/local/bin/brew
  register: homebrew_check

- name: Installing Homebrew
  become: false
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  when:
    - not homebrew_check.stat.exists

- name: Updating Homebrew
  become: false
  community.general.homebrew:
    update_homebrew: true
  when: homebrew_check.stat.exists
