---
- name: check OS details
  debug:
    msg: '{{ ansible_distribution }} - {{ ansible_distribution_major_version }}'

- name: setup users defaults
  ansible.builtin.include_tasks:
    file: users.yml
    apply:
      become: true

- name: fedora dnf config
  ansible.builtin.include_tasks:
    file: fedora-default-config.yml
    apply:
      become: true
  when: ansible_distribution == "Fedora"

- name: packages update
  ansible.builtin.include_tasks:
    file: update-packages-cache.yml
    apply:
      become: true

- name: upgrade all packages
  ansible.builtin.include_tasks:
    file: upgrade-packages.yml
    apply:
      become: true

- name: setup additional repository for Fedora
  ansible.builtin.include_tasks:
    file: fedora-repository.yml
    apply:
      become: true
  when: ansible_distribution == "Fedora"

- name: setup essential packages
  ansible.builtin.include_tasks:
    file: essential-packages.yml
    apply:
      become: true

- name: setup essential packages for Fedora
  ansible.builtin.include_tasks:
    file: fedora-essentials.yml
    apply:
      become: true
  when: ansible_distribution == "Fedora"

- name: homebrew setup
  ansible.builtin.include_tasks:
    file: homebrew-setup.yml
    apply:
      become: true

- name: flatpak packages
  ansible.builtin.include_tasks:
    file: flatpak-packages.yml
