---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml
    requirements-file: collections.yml

# driver:
#   name: vagrant
#   provider:
#     name: libvirt
#     type: libvirt
#     options:
#       memory: 192
#       cpus: 2
# platforms:
#   - name: debian
#     box: debian/bullseye64
#     interfaces:
#       - auto_config: true
#         network_name: private_network
#         type: static
#         ip: 192.168.10.10

driver:
  name: docker
platforms:
  - name: Fedora
    image: docker.io/fedora:39
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    pre_build_image: true
  - name: Ubuntu
    image: docker.io/ubuntu:jammy
    cmd: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    privileged: true
    pre_build_image: false
    override_command: false
  - name: Debian
    image: docker.io/debian:bookworm
    cmd: /lib/systemd/systemd
    tmpfs:
      - /run
      - /tmp
    privileged: true
    pre_build_image: false
    override_command: false
provisioner:
  name: ansible
  log: true
  instance:
    ansible_user: ansible
  scenario:
    name: default
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
