---
- hosts: localhost
  become: true
  pre_tasks: []
  roles:
    # - core-options
    # - core-packages
  tasks:
    - name: setup core options
      ansible.builtin.include_role:
        name: core-options
    - name: setup core packages
      ansible.builtin.include_role:
        name: core-packages
    - name: setup cli tools
      ansible.builtin.include_role:
        name: core-dev
      vars:
        zsh: false
        dotnet: false
        jdk: false
        nodejs: false
        php: false
    # - name: setup core desktop packages
    #   ansible.builtin.include_role:
    #     name: desktop-packages
    # - name: setup desktop tools
    #   ansible.builtin.include_role:
    #     name: desktop-tools
    # - name: setup desktop ide's
    #   ansible.builtin.include_role:
    #     name: desktop-ide
