---
scenario:
  name: shared
driver:
  name: docker
platforms:
  - name: ansible-role-zsh-debian-10
    image: geerlingguy/docker-debian10-ansible
    pre_build_image: true

  - name: ansible-role-zsh-1604
    image: geerlingguy/docker-ubuntu1604-ansible
    pre_build_image: true

  - name: ansible-role-zsh-1804
    image: geerlingguy/docker-ubuntu1804-ansible
    pre_build_image: true

  - name: ansible-role-zsh-2004
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true

  - name: ansible-role-zsh-centos-8
    image: geerlingguy/docker-centos8-ansible

provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
  inventory:
    group_vars:
      all:
        zsh_shared: yes
