---
driver:
  name: docker
platforms:
  - name: ansible-role-zsh-debian-10
    image: geerlingguy/docker-debian10-ansible
    pre_build_image: true

  - name: ansible-role-zsh-1604
    image: geerlingguy/docker-ubuntu1604-ansible
    pre_build_image: true

  - name: ansible-role-zsh-1804
    image: geerlingguy/docker-ubuntu1804-ansible
    pre_build_image: true

  - name: ansible-role-zsh-2004
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true

  - name: ansible-role-zsh-centos-8
    image: geerlingguy/docker-centos8-ansible

#driver:
#  name: vagrant
#  provider:
#    name: virtualbox
#platforms:
#  - name: xenial64
#    box: bento/ubuntu-16.04

#verifier:
#  name: testinfra

provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
  inventory:
    group_vars:
      all:
        zsh_user: root
        zsh_mc_solarized_skin: yes
        zsh_antigen_bundles_extras:
          - { name: test/in-list, when: true }
          - { name: test/not-in-list, when: false }
          - { name: test/command-exists, command: zsh }
          - { name: test/command-not-exists, command: not-exists-commanddd }
