version: '3.9'

networks:
  proxy:
    name: traefik_net
    external: true

services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
    volumes:
      - "{{ protrack_data_path }}:/var/lib/mysql"
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == {{ core_hostname }}
      resources:
        limits:
          cpus: "0.2"
          memory: 512M
        reservations:
          cpus: "0.025"
          memory: 256M
