---
- name: jetbrains apps setup
  ansible.builtin.include_tasks:
    file: setup-jetbrains.yml
    apply:
      become: false

- name: vscode setup
  ansible.builtin.include_tasks:
    file: setup-vscode.yml
    apply:
      become: false

