---
- name: Add swarm masters to bootstrapped cluster
  docker_swarm:
    state: join
    debug: yes
    remote_addrs: "{{ hostvars[groups.docker[0]]['ansible_default_ipv4']['address'] }}"
    join_token: "{{ swarm_info.swarm_facts.JoinTokens.Manager }}"
    advertise_addr: "{{ ansible_default_ipv4.address }}"
  when: swarm_master is defined and swarm_master|bool == True
