---
- name: remove conflicting ubuntu pacakges
  apt:
    pkg:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
      - docker-compose
    state: absent
- name: install needed pip modules
  pip:
    name:
      - docker
    extra_args: --user --break-system-packages
- name: add GPG key
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
- name: add docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
    filename: docker
- name: install docker and required packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest
    update_cache: true
- name: ensure docker service is started
  service:
    name: docker
    state: started
    enabled: yes
  notify:
    - restart_docker
- name: configure docker options
  template:
    src: docker-daemon.json.j2
    dest: "/etc/docker/daemon.json"
    backup: true
    mode: 0644
  notify:
    - restart_docker

- name: "setup docker compose"
  shell: "{{ item }}"
  become: true
  with_items:
    - rm -rf /usr/local/bin/docker-compose
    - sudo curl -L "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - chmod +x /usr/local/bin/docker-compose
    - /usr/local/bin/docker-compose --version

- name: add docker group members
  become: true
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  with_items: "{{ docker_groupmembers }}"
