---
- name: setup essential packages for Fedora
  ansible.builtin.include_tasks:
    file: fedora-essentials.yml
    apply:
      become: true
  when: ansible_distribution == "Fedora"

- name: flatpak packages
  ansible.builtin.include_tasks:
    file: flatpak-packages.yml
